version: 0.0
os: linux

files:
  - source: /
    destination: /opt/room
permissions:
  - object: /opt/room/
    owner: centos
    group: centos
    mode: 755
hooks:
  AfterInstall:
    # location은 프로젝트의 root경로를 기준
    - location: ./deploy/room_api_server_deploy.sh
    - location: ./deploy/room_socket_server_deploy.sh
      timeout: 60
      runas: root

