# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

env:
  PROJECT_NAME: Room

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    name: CI
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # java install
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # maven
      - name: Grant execute permission for mvnw
        run: chmod +x mvnw
        shell: bash

      - name: Build with Maven
        run: ./mvnw package
        shell: bash

      # install node
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: build frond
        run: |
          cd ./room-front
          npm i
          npm build
